name: Deny

on:
  push:
    branches:
      - '*'
    paths:
      - '**/Cargo.lock'
      - '**/Cargo.toml'
      - '**/deny.toml'
  pull_request:
    branches:
      - master
    paths:
      - '**/Cargo.lock'
      - '**/Cargo.toml'
      - '**/deny.toml'

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: EmbarkStudios/cargo-deny-action@v2.0.17
        with:
          command: check licenses
